### ISSUE TITLE
Validation of ProductCode

### ISSUE THREAD

**Issue by matbech** [microsoft/winget-create#140]
# Brief description of your issue
winget-create should validate the ProductCode. It should check for an empty ProductCode and fail validation.

# Steps to reproduce
Create a manifest with an empty ProductCode. 

```
- InstallerLocale: en-US
  Platform:
  - Windows.Desktop
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://bla.msi
  InstallerSha256: 434242....
  ProductCode: ''
```

Example:
https://github.com/matbech/winget-pkgs/blob/1fa3e53c311f9215207787e8f38f9f2f8680aef7/manifests/s/SmartSoft/SmartFTP/10.0.2908.0/SmartSoft.SmartFTP.yaml

# Expected behavior
validation of the manifest should fail

# Actual behavior
manifest is submitted

**Comment by ryfu-msft** [comment]
Hey @matbech,

It turns out that it is not possible to validate a ProductCode as it is simply a string that we match against registry key names. However, you did point out that we should not allow fields with empty strings to be shown in the outputted manifest. I have addressed those issues in PR #208. Thanks for your suggestion!
