### ISSUE TITLE
`wingetcreate submit` should delete autogenerated branch

### ISSUE THREAD

**Issue by matbech** [microsoft/winget-create#141]
# Description of the new feature/enhancement
`wingetcreate submit` should delete the autogenerated GIT branch after the PR has been submitted. If not done by default, a command line option should be provided. The PR outlives the branch it was submitted from even if the branch no longer exists.

**Comment by jedieaston** [comment]
Deleting the branch on GitHub closes the PR regardless of whether it is merged or not. If wingetcreate automatically deleted it upon submission, the PR wouldn't be able to be merged. Maybe a way to do it would be to have a `wingetcreate cleanup` command where it uses the GitHub API to check your fork and find branches that start with `autogenerated/`, check if they are attached to a open PR, and then delete them if they are not.

(as I understand it, because I've gotten bitten by this before. I've tried to go and clean up my branches and accidentally close one that is attached to a open PR and it gets closed with no warning on github.com).

**Comment by matbech** [comment]
Good point, I was under the (wrong) assumption that deleting the branch wouldn't close the PR. But apparently this is not the case.
There is a setting in the repo:
```
[x] After pull requests are merged, you can have head branches deleted automatically.
Automatically delete head branches
```
Maybe it does what I want.
