### ISSUE TITLE
PR includes old version in title rather than new version

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-create#148]
# Brief description of your issue

@DHowett reported
>Hey, uh, wingetcreate gives the PR the name of the OLD version instead of the new one!

https://github.com/microsoft/winget-pkgs/pull/26459#issuecomment-909419700

# Expected behavior

The PR for a new version should report the new version.

# Actual behavior

The PR reported the previous version.

**Comment by ryfu-msft** [comment]
Looking at the mentioned PR, it looks like only the --url flag was used to update the urls, but not the version flag (--version). This is why the initial commit only shows changes for the installers and not for the packageVersion. 

Because of this, there is no change in the manifest's packageVersion, which is why the PR title defaults to using the version from the old manifest. I believe this can be resolved by also specifying the new version with the --version flag. This would also ensure that the packageVersions in each manifest are correctly updated too.

**Comment by DHowett** [comment]
> Looking at the mentioned PR, it looks like only the --url flag was used to update the urls, but not the version flag (--version). This is why the initial commit only shows changes for the installers and not for the packageVersion.
> 
> Because of this, there is no change in the manifest's packageVersion, which is why the PR title defaults to using the version from the old manifest. I believe this can be resolved by also specifying the new version with the --version flag. This would also ensure that the packageVersions in each manifest are correctly updated too.

So, quick question. Why is that a reasonable behavior? :smile:

A manifest, once published, should be immutable. wingetcreate _update_ should, unless explicitly instructed, do its best to assume you literally meant "i want a new version of this package"... and I don't totally know why it decides to replace the old version _with_ the new version? It can clearly determine the version it is supposed to be operating on, after all...

**Comment by DHowett** [comment]
Right. My mental model of this tool was: "I only need to specify the version if it cannot be determined from the file. It will do the right thing if it detects a newer version.". It was a surprise that "--version" _actually_ means "create a new version on the other end, and use this installer.". It was even more of a surprise when it _detected the right version number_ on top of all of that. :smile:
