### ISSUE TITLE
allow us to do singleton files

### ISSUE THREAD

**Issue by solomoncyj** [microsoft/winget-create#272]
### Description of the new feature / enhancement

allow us to do singleton files in wingetcreate, maybe through a y/n question at the end if there is only 1 installer? it would save the hassle of editing each file if a pr goes wrong

**Comment by denelon** [comment]
@solomoncyj 

The decision to create multiple files was intentional. This is more inclusive for localizing the metadata and simplifies challenges when converting from a singleton to a multi-file manifest. The manifest can be edited directly using wingetcreate. What kinds of problems have you encountered?

**Comment by solomoncyj** [comment]
If i made a mistake, i might need to edit all 3 of the files

**Comment by denelon** [comment]
The Windows Package Manager Manifest Creator should handle that for you. The only values spanning all the files are the "packageIdentifier" and "packageVersion" and the version of schema used. That's why I was looking for specific problems. If there is a bug, we need to fix it 😊

We're hoping authors don't need to make manual changes to manifest files. That's why we built the tool. Singleton manifests just don't have the ability to express the richness of metadata when compared with the multi-file format. We are also likely to deprecate the support for singletons from the Windows Package Manager Community Repository. The client would still be able to parse them, but they would have limited value in most cases.
