### ISSUE TITLE
`wingetcreate update` different `InstallerType`

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-create#75]
# Brief description of your issue
When you do `wingetcreate update --id --version --url https://endswith.msi` on a manifest which have `https://endwith.exe` the InstallerType and InstallerSwitches will remain with the exe switches.

# Steps to reproduce
`wingetcreate update -i TechSmith.Camtasia -v 21.0.4.31371 -u https://download.techsmith.com/camtasiastudio/releases/2104/camtasia.msi`

# Expected behavior
Replace the EXE Installer or keep the EXE installer (try to update it) and add the MSI installer.

# Actual behavior
Only replaces `InstallerUrl` and `InstallerSha256`

# Environment
Windows Manifest Creator v0.1.0.1

```none
Windows Package Manager Manifest Creator version? (wingetcreate.exe -?)

Any other software?
```

**Comment by ryfu-msft** [comment]
Hey @OfficialEsco,

We don't currently support this behavior so we show a friendly error message to the user, but we do have plans to add this functionality. The reason is because we want to preserve updating with multiple installers. We don't want to risk replacing the wrong installer and we also can't tell if the user wants to replace an existing installer or add a new one. I believe this needs to be addressed in a new `modify` command which I have roughly outlined here #111.
